{
 "title": "Grafana Dashboard for Open WebUI",
 "description": "A complete, opensource dashboard that shows consumption and usage of Open WebUI.",
 "tags": [
  "genAI",
  "AI",
  "Open WebUI",
  "Llama",
  "DeepSeek",
  "Qwen"
 ],
 "time": { "from": "2025-01-11T16:36:00.428Z", "to": "2025-02-15T16:44:17.552Z" },
 "templating": {
  "list": [
   {
    "name": "model",
    "label": "LLM Model",
    "query": {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"model\"] != \"\")\r\n  |> filter(fn: (r) => r[\"model\"] != \"unknown\")\r\n  |> keep(columns: [\"model\"])\r\n  |> distinct(column: \"model\")\r\n  |> group()"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "<a href=\"https://openwebui.com/\" target=\"_blank\"><img src=\"https://openwebui.com/user.png\" alt=\"drawing\" width=\"200\"/></a>"
   }
  },
  {
   "title": "Open WebUI Usage Overview",
   "type": "stat",
   "description": "Displays key usage statistics for Open WebUI, including model count, evaluation counts, average response tokens, and average processing time, aiding in monitoring and optimization.",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> keep(columns: [\"model\"])\r\n  |> distinct(column: \"model\")\r\n  |> group()\r\n  |> count()"
    },
    {
     "query": "evalCountSum = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"evalCount\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> group(columns: [])\r\n  |> sum()\r\n\r\npromptEvalCountSum = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"promptEvalCount\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> group(columns: [])\r\n  |> sum()\r\n\r\nunion(tables: [evalCountSum, promptEvalCountSum])\r\n  |> group(columns: [])\r\n  |> sum()"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTokens\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> group(columns: [])\r\n  |> mean()"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"approximateTotalMS\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> group(columns: [])\r\n  |> mean()"
    }
   ]
  },
  {
   "title": "Token Usage by Model",
   "type": "bargauge",
   "description": "Displays token usage across models, highlighting consumption levels for Open WebUI in an intuitive bar gauge format.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "evalCountSum = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"evalCount\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> group(columns: [\"model\"])  \r\n  |> sum()\r\n\r\npromptEvalCountSum = from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"promptEvalCount\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> group(columns: [\"model\"]) \r\n  |> sum()\r\n\r\nunion(tables: [evalCountSum, promptEvalCountSum])\r\n  |> group(columns: [\"model\"])\r\n  |> sum()\r\n  |> filter(fn: (r) => r[\"_value\"] > 0)\r\n  |> rename(columns: {\"_value\": \"\"})\r\n  |> yield(name: \"filtered_tokens_by_model\")"
    }
   ]
  },
  {
   "title": "Model Evaluation Counts",
   "type": "timeseries",
   "description": "This panel illustrates the usage patterns of various LLM models in Open WebUI by tracking and displaying evaluation counts over time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"evalCount\")\r\n  |> filter(fn: (r) => r[\"model\"] != \"unknown\")\r\n  |> filter(fn: (r) => r[\"_value\"] > 0)\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> group(columns: [\"model\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "LLM Response Historical",
   "type": "timeseries",
   "description": "Displays the count of LLM tokens, helping to monitor the usage trends of different models over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"evalCount\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> filter(fn: (r) => r[\"_value\"] > 0)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> yield(name: \"tokens_per_minute\")\r\n"
    },
    {
     "query": "from(bucket: \"telegraf\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"promptEvalCount\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> aggregateWindow(every: 1m, fn: sum, createEmpty: false)\r\n  |> filter(fn: (r) => r[\"_value\"] > 0)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> yield(name: \"tokens_per_minute\")\r\n"
    }
   ]
  },
  {
   "title": "Prompt Tokens per Second",
   "type": "timeseries",
   "description": "Monitors the rate of prompt token usage per second in Open WebUI, helping track real-time consumption and efficiency of different models.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"promptTokens\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false) \r\n  |> filter(fn: (r) => r[\"_value\"] > 0)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> yield(name: \"tokens_per_second\")\r\n"
    }
   ]
  },
  {
   "title": "Response Tokens per Second",
   "type": "timeseries",
   "description": "Monitors the rate at which response tokens are generated by Open WebUI models, helping identify trends in performance and token usage over time.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"responseTokens\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false) \r\n  |> filter(fn: (r) => r[\"_value\"] > 0)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> yield(name: \"tokens_per_second\")\r\n"
    }
   ]
  },
  {
   "title": "Average Duration",
   "type": "timeseries",
   "description": "Displays the average duration of tasks or processes in Open WebUI, helping users assess performance over time by aggregating data for better insight.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"openwebui_stats\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"approximateTotalMS\")\r\n  |> filter(fn: (r) => r[\"model\"] =~ /${model:regex}/)\r\n  |> filter(fn: (r) => r[\"_value\"] > 0)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> yield(name: \"mean_duration\")\r\n"
    }
   ]
  }
 ]
}