
FROM mcr.microsoft.com/devcontainers/universal:2 as builder_venv_drant

# Create the venv
RUN python -m venv /opt/venv

# Activate the venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip --no-cache-dir install -U pip \
    && pip install -r https://raw.githubusercontent.com/ygo74/searchbot/main/qdrant/requirements.txt


# Images
FROM mcr.microsoft.com/devcontainers/universal:2

COPY --from=builder_venv_drant /opt/venv /opt/qdrant_linux_venv

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONBUFFERED=1